---

- name: installing go from homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - go

- name: set go env
  lineinfile: dest=~/.shrc line='{{ item }}'
  with_items:    
    - "export GOPATH=$HOME/.cache/go:$HOME"
    - "export PATH=$PATH:/usr/local/go/bin:$HOME/.cache/go/bin:$HOME/bin"

- name: make dir ~/src
  file: path=~/src state=directory

# - name: source go env
#   command: pwd && source ~/.shrc

- name: go get some packages
  ignore_errors: yes
  shell: |
    pwd && source ~/.shrc
    go get -u golang.org/x/tools/cmd/godoc
    #go get -u golang.org/x/tools/cmd/vet
    go get github.com/golang/lint/golint