---

- name: Install Brew Cask packages
  ignore_errors: yes
  homebrew_cask: name={{ item }} state=present
  with_items:
    - visual-studio-code
    
- name: Install code packages
  command: code --install-extension {{ item }}
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
  with_items:
    - DavidAnson.vscode-markdownlint
    - PeterJausovec.vscode-docker
    - dbaeumer.vscode-eslint
    - eg2.vscode-npm-script
    - felipecaputo.git-project-manager
    - msjsdiag.debugger-for-chrome
    - wayou.vscode-todo-highlight