---

- name: Ensures tmp/dpkg dir exists
  file: path="/home/{{ ansible_env.USER }}/tmp/dpkg/" state=directory
# - name: "Check if {{ item.name }} is installed"
#   command: "dpkg-query -W {{ item.name }}"
#   register: "{{ item.name }}_check_deb"
#   failed_when: "{{ item.name }}_check_deb.rc > 1"
#   changed_when: "{{ item.name }}_check_deb.rc == 1"

- name: Download {{ item.name }}
  get_url: 
    url={{ item.url }}
    dest="/home/{{ ansible_env.USER }}/tmp/dpkg/{{ item.name }}.deb"
  ignore_errors: true
  async: 45
  poll: 5
  # when: "{{ item.name }}_check_deb.rc == 1"

- name: install {{ item.name }}
  become: true
  become_method: sudo
  ignore_errors: true
  apt: deb="/home/{{ ansible_env.USER }}/tmp/dpkg/{{ item.name }}.deb"
  async: 45
  poll: 5