---

- name: Ensures Downloads/dpkg dir exists
  file: path="/home/{{ ansible_env.USER }}/Downloads/dpkg/" state=directory
- name: "Check if {{ item.name }} is installed"
  command: "dpkg-query -W {{ item.name }}"
  register: "{{ item.name }}_check_deb"
  failed_when: "{{ item.name }}_check_deb.rc > 1"
  changed_when: "{{ item.name }}_check_deb.rc == 1"
- name: Download {{ item.name }}
  get_url: 
    url={{ item.url }}
    dest="/home/{{ ansible_env.USER }}/Downloads/dpkg/{{ item.name }}.deb"
  when: "{{ item.name }}_check_deb.rc == 1"
- name: Install {{ item.name }}
  become: true
  become_method: sudo
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/dpkg/{{ item.name }}.deb"
  when: "{{ item.name }}_check_deb.rc == 1"