---

- name: Ensures tmp/extract dir exists
  file: path="/home/{{ ansible_env.USER }}/.local/share/{{ item.name }}" state=directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{ item.url }}"
    dest: "/home/{{ ansible_env.USER }}/.local/share/{{ item.name }}/"
    remote_src: yes