---

- name: Ensures tmp/extract dir exists
  file: path="/home/{{ ansible_env.USER }}/.local/share/{{ item.name }}" state=directory

- name: download and extract {{ item.name }}
  unarchive:
    src: "{{ item.url }}"
    dest: "/home/{{ ansible_env.USER }}/.local/share/{{ item.name }}/"
    remote_src: yes