---

- name: install nix
  shell: curl https://nixos.org/nix/install | sh
  args: 
    warn: false
    
- shell: . /Users/me/.nix-profile/etc/profile.d/nix.sh
  tags: mac

- name: add nix to path
  blockinfile:
    path: ~/.shrc
    create: yes
    block: source /Users/me/.nix-profile/etc/profile.d/nix.sh