---

- name: Show hidden files in finder by default
  tags: mac
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true state=present

- name: Reduce keyboard key repeat delay
  tags: mac
  osx_defaults: key=InitialKeyRepeat type=int value=15 state=present

- name: osx defaults
  tags: mac
  shell: |
    defaults write com.apple.dock show-recents -bool no
    defaults write com.apple.dock recent-apps -array # intentionally empty
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -string true

- name: Increase keyboard key repeat speed
  tags: mac
  osx_defaults: key=KeyRepeat type=int value=2

- name: Set cron shell
  cron: name=SHELL env=yes value=/bin/zsh

- name: Set cron path
  cron: name=PATH env=yes value=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

- name: create karabiner config folder
  tags: mac
  file: path="~/.karabiner.d/configuration" state=directory
- name: karabiner configuration
  tags: mac
  copy:
    src: karabiner.json
    dest: ~/.karabiner.d/configuration/karabiner.json

- name: generate ssh key
  ignore_errors: yes
  shell: ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ""

- name: create xmodmap config folder
  tags: ubuntu
  file: path="~/.config/xmodmap" state=directory
- name: xmodmap configuration script
  tags: ubuntu
  copy:
    src: xmodmapscript.sh
    dest: ~/.config/xmodmap/xmodmapscript.sh
- name: make xmodmapscript executable
  tags: ubuntu
  file:
    path: ~/.config/xmodmap/xmodmapscript.sh
    mode: 0755
- name: add xmodmapinit to startup applications
  tags: ubuntu
  copy:
    src: xmodmapinit.desktop
    dest: ~/.config/autostart/xmodmapinit.desktop

- name: phone into .ssh/config
  blockinfile:
    dest: ~/.ssh/config
    create: yes
    marker: "# {mark} phone (simpleSSHD)"
    block: |
      Host phone
        HostName 192.168.1.2
        User tissot_sprout
        Port 2222





