---

- name: Install packages from Homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - docker-compose
    - virtualbox

- name: Install Brew Cask packages
  ignore_errors: yes
  homebrew_cask: name={{ item }} state=present
  with_items:
    - vagrant
    - docker