---

- name: Show hidden files in finder by default
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true state=present
  tags: mac

- name: Reduce keyboard key repeat delay
  osx_defaults: key=InitialKeyRepeat type=int value=15 state=present
  tags: mac

- name: Increase keyboard key repeat speed
  osx_defaults: key=KeyRepeat type=int value=2
  tags: mac

- name: Set cron shell
  cron: name=SHELL env=yes value=/bin/zsh

- name: Set cron path
  cron: name=PATH env=yes value=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

- name: create karabiner config folder
  file: path="~/.karabiner.d/configuration" state=directory
- name: karabiner configuration
  tags: mac
  copy:
    src: karabiner.json
    dest: ~/.karabiner.d/configuration/karabiner.json

- name: generate ssh key
  shell: ssh-keygen -t rsa -f .ssh/id_rsa -P ""




