---

- include_vars: backups_gl_access.yml
  tags: debug
- name: Ensures tmp/access dir exists
  tags: debug
  file: path="/home/{{ ansible_env.USER }}/tmp/access/" state=directory
- name: download access
  tags: debug
  get_url:
    url: "{{ access_file_url }}"
    headers:
      PRIVATE-TOKEN: "{{ gl_token }}"
    dest: "/home/{{ ansible_env.USER }}/tmp/access/duplicati_access.yml"
    force: yes
- include_vars: "/home/{{ ansible_env.USER }}/tmp/access/duplicati_access.yml"
  tags: debug
- shell: "echo {{ accounts_example_secret }}"

- name: nono
  tags: debug
  copy:
    dest: "~/.cache/duplicati/{{item.name}}-duplicati-config.json"
    content: |
      {
        "CreatedByVersion": "2.0.1.53",
        "Schedule": {
          "ID": 5,
          "Tags": [
            "ID=6"
          ],
          "Time": "2017-03-30T13:00:00Z",
          "Repeat": "10D",
          "LastRun": "2017-03-20T13:00:00Z",
          "Rule": "AllowedWeekDays=Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
          "AllowedDays": [
            "mon",
            "tue",
            "wed",
            "thu",
            "fri",
            "sat",
            "sun"
          ]
        },
        "Backup": {
          "ID": "6",
          "Name": "{{ item.name }}",
          "Tags": [],
          "TargetURL": "mega://duplicati/{{ item.name }}?{{ duplicati_parameter_name_account_username }}={{ item.user }}%40{{ accounts_email_domain }}&{{ duplicati_parameter_name_account_secret }}={{ accounts_example_secret }}",
          "DBPath": "/home/{{ ansible_env.USER }}/.config/Duplicati/{{ (item.sources | checksum)[0:10] }}.sqlite",
          "Sources": {{ item.sources }},
          "Settings": [
            {
              "Filter": "",
              "Name": "encryption-module",
              "Value": "aes",
              "Argument": null
            },
            {
              "Filter": "",
              "Name": "compression-module",
              "Value": "zip",
              "Argument": null
            },
            {
              "Filter": "",
              "Name": "dblock-size",
              "Value": "50mb",
              "Argument": null
            },
            {
              "Filter": "",
              "Name": "passphrase",
              "Value": "{{ duplicati_example_secret }}",
              "Argument": null
            },
            {
              "Filter": "",
              "Name": "keep-versions",
              "Value": "1",
              "Argument": null
            }
          ],
          "Filters": [],
          "Metadata": {
            "LastDuration": "00:04:51.1315780",
            "LastStarted": "20170325T185418Z",
            "LastFinished": "20170325T185910Z",
            "LastBackupDate": "20170325T185419Z",
            "BackupListCount": "1",
            "TotalQuotaSpace": "0",
            "FreeQuotaSpace": "0",
            "AssignedQuotaSpace": "-1",
            "TargetFilesSize": "582994965",
            "TargetFilesCount": "25",
            "TargetSizeString": "555,99 MB",
            "SourceFilesSize": "1506444094",
            "SourceFilesCount": "177885",
            "SourceSizeString": "1,40 GB",
            "LastBackupStarted": "20170325T185418Z",
            "LastBackupFinished": "20170325T185910Z",
            "LastErrorDate": "20170325T184702Z",
            "LastErrorMessage": "API response: QuotaExceeded"
          },
          "IsTemporary": false
        },
        "DisplayNames": {
          {{ item.sources | map('regex_replace', '^(.*)$','"\1":"\1"') | list | join(',') }}
        }
      }

  with_items:
    - name: src
      user: anon1
      sources: 
        - "/home/{{ansible_env.USER}}/src"

    - name: Documents
      user: anon1
      sources: 
        - "/home/{{ansible_env.USER}}/Documents"

    - name: Downloads
      user: anon2
      sources: 
        - "/home/{{ansible_env.USER}}/Downloads"

    - name: Graphisme
      user: anon1
      sources: 
        - "/home/{{ansible_env.USER}}/Graphisme"
        
    - name: photos_autres
      user: anon1
      sources: 
        - "/home/{{ansible_env.USER}}/photos_autres"

    - name: Photos
      user: anon1
      sources: 
        - "/home/{{ansible_env.USER}}/Photos"

    - name: upload
      user: anon4
      sources: 
        - "/home/{{ansible_env.USER}}/upload"
    
    - name: windows
      user: anon2
      sources: 
        - "/home/{{ansible_env.USER}}/windows"

    - name: music_1
      user: anon3
      sources:
        - "/home/{{ansible_env.USER}}/Musique"
        - "/home/{{ansible_env.USER}}/Musique/80's Hits/"
        - "/home/{{ansible_env.USER}}/Musique/Blues/"
        - "/home/{{ansible_env.USER}}/Musique/80's Hits.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Alternative Rock.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Alternative Rock/"
        - "/home/{{ansible_env.USER}}/Musique/Blues.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Brass Band/"
        - "/home/{{ansible_env.USER}}/Musique/Classic Rock/"
        - "/home/{{ansible_env.USER}}/Musique/Brass Band & Swing.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Classic Rock.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Classique/"
        - "/home/{{ansible_env.USER}}/Musique/Country/"
        - "/home/{{ansible_env.USER}}/Musique/Country.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Dancefloor/"
        - "/home/{{ansible_env.USER}}/Musique/Dancefloor.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Downloads/"
        - "/home/{{ansible_env.USER}}/Musique/Electro/"
        - "/home/{{ansible_env.USER}}/Musique/Electro-Swing/"
        - "/home/{{ansible_env.USER}}/Musique/Electro-Swing & Dub/"
        - "/home/{{ansible_env.USER}}/Musique/Folk Rock/"
        - "/home/{{ansible_env.USER}}/Musique/Electro.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Funk & Soul/"
        - "/home/{{ansible_env.USER}}/Musique/Gypsy Music/"

    - name: music_2
      user: anon5
      sources:
        - "/home/{{ansible_env.USER}}/Musique/Ska/"
        - "/home/{{ansible_env.USER}}/Musique/RockLegends1/"
        - "/home/{{ansible_env.USER}}/Musique/Rock n' Roll.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Rock n' Roll/"
        - "/home/{{ansible_env.USER}}/Musique/Reggae.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Reggae/"
        - "/home/{{ansible_env.USER}}/Musique/Rap & RnB.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Rap & RnB/"
        - "/home/{{ansible_env.USER}}/Musique/Radios.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Punk Rock.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Punk Rock/"
        - "/home/{{ansible_env.USER}}/Musique/Post Punk/"
        - "/home/{{ansible_env.USER}}/Musique/Pop Rock.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Pop Rock/"
        - "/home/{{ansible_env.USER}}/Musique/Pop/"
        - "/home/{{ansible_env.USER}}/Musique/Piano.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Original Soundtrack/"
        - "/home/{{ansible_env.USER}}/Musique/Old Times Rock n'Roll.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Odd/"
        - "/home/{{ansible_env.USER}}/Musique/OST.m3u"
        - "/home/{{ansible_env.USER}}/Musique/New Playlist.m3u"
        - "/home/{{ansible_env.USER}}/Musique/New Playlist (2).m3u"
        - "/home/{{ansible_env.USER}}/Musique/Metal.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Metal/"
        - "/home/{{ansible_env.USER}}/Musique/Mashup/"
        - "/home/{{ansible_env.USER}}/Musique/Latin & Gypsy Music/"
        - "/home/{{ansible_env.USER}}/Musique/Jazz/"
        - "/home/{{ansible_env.USER}}/Musique/Indie Rock.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Indie Rock/"
        - "/home/{{ansible_env.USER}}/Musique/Hard Rock.m3u"
        - "/home/{{ansible_env.USER}}/Musique/Hard Rock/"