---

- name: Update brew daily
  tags: mac
  cron: name="brew autoupdate" special_time="daily"
        job="/usr/local/bin/brew update"

- name: Cleanup brew
  tags: mac
  cron: name="brew cleanup" special_time="monthly"
        job="/usr/local/bin/brew cleanup"

- name: Install packages from Homebrew
  tags: mac
  homebrew: name={{ item }} state=present
  with_items:
    - httpie
    - node
    - npm
    - yarn
    - jq
    - python
    - python3
    - go
    - docker-compose
    - kubectl

- name: Install Brew Cask packages
  tags: mac
  ignore_errors: yes
  homebrew_cask: name={{ item }} state=present
  with_items:
    - java
    - alfred
    - vagrant
    - google-chrome
    - firefox
    - iterm2
    - sequel-pro
    - docker
    - hyper
    - etcher
    - android-sdk
    - visual-studio-code
    - gitkraken
    - virtualbox
    - deluge
    - karabiner-elements
    - todoist
    - postico
    - postman
    - minikube
    
