---

# - name: install python-apt (needed for ansible)

- apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
- name: chrome
  apt: name=google-chrome state=present


- name: install packages on ubuntu
  apt: name={{ item }} state=present
  with_items:
    # - google-chrome-stable
    - gitkraken
    - lib32z1 lib32ncurses5 lib32stdc++6