---

# - name: install python-apt (needed for ansible)

# - apt_repository:
#     repo: deb http://dl.google.com/linux/chrome/deb/ stable main
#     state: present
#     filename: google-chrome
# - name: chrome
#   apt: name=google-chrome state=present

- include: "{{ role_path }}/modules/getDpkg.yml"
  tags: ubuntu
  with_items:
    - { name: 'chrome', url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' }
    - { name: 'gitkraken', url: 'https://release.gitkraken.com/linux/gitkraken-amd64.deb' }


# - name: install packages on ubuntu
#   tags: ubuntu
#   apt: name={{ item }} state=present
#   with_items:
#     # - gitkraken
#     # - lib32z1 lib32ncurses5 lib32stdc++6

- name: install packages on ubuntu
  tags: ubuntu
  apt: name={{ item }} state=present
  become: true
  become_method: sudo
  with_items:
    - xclip