---

- name: shell functions for mac
  blockinfile:
    dest: ~/.shrc
    create: yes
    marker: "# ANSIBLE {mark} shell functions for mac"
    block: |
      installDmgFromUrl() {
          URL=$1
          dmg=$(mktemp)
          wget -O ${dmg} $URL
          mountPoint=/Volumes/$(openssl rand -hex 16)
          echo ${mountPoint}
          hdiutil attach ${dmg} -mountpoint ${mountPoint}
          cd ${mountPoint}

          # install any .pkg
          sudo installer -pkg $(find *.pkg) -target "/"

          # install any .app
          for app in $(find ${mountPoint} -type d -maxdepth 2 -name \*.app); do
              cp -a ${app} /Applications/
          done

          hdiutil detach ${mountPoint}
          rm ${dmg}
      }
      extract() {
        if [ -z "$1" ]; then
          echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
        else
          if [ -f $1 ] ; then
            if [ $# -eq 2 ]; then 
              DEST=$2
            else 
              DEST=${1%.*}
            fi

            case $1 in
            # *.tar.bz2)   tar xvjf ../$1    ;;
            *.tar.gz)    tar -xvzf ${DEST} $1    ;;
            # *.tar.xz)    tar xvJf ../$1    ;;
            # *.lzma)      unlzma ../$1      ;;
            # *.bz2)       bunzip2 ../$1     ;;
            # *.rar)       unrar x -ad ../$1 ;;
            # *.gz)        gunzip ../$1      ;;
            *.tar)       tar -xvf ${DEST} $1     ;;
            # *.tbz2)      tar xvjf ../$1    ;;
            *.tgz)       tar -xvzf ${1} --directory=${DEST}    ;;
            *.zip)       unzip -d ${DEST} $1      ;;
            # *.Z)         uncompress ../$1  ;;
            *.7z)        7z x $1 -o${DEST}        ;;
            # *.xz)        unxz ../$1        ;;
            # *.exe)       cabextract ../$1  ;;
            *)           echo "extract: '$1' - unknown archive method" ;;
            esac
          else
            echo "$1 - file does not exist"
          fi
        fi
      }

- name: mac aliases
  blockinfile:
    dest: ~/.shrc
    create: yes
    marker: "# {mark} alias {{item.key}}"
    block: |
      alias {{ item.key }}="{{ item.value }}"
  with_dict: "{{aliases}}"
  vars:
    aliases:
      copy_ssh: "cat ~/.ssh/id_rsa.pub | pbcopy"
      chrome: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
