---

- name: install docker-compose from brew
  tags: mac
  homebrew: name=docker-compose state=present


- name: install Brew Cask packages
  tags: mac
  ignore_errors: yes
  homebrew_cask: name={{ item }} state=present
  with_items:
    - vagrant
    - docker
    - virtualbox

# - name: Create system aliases
#   lineinfile: dest=~/.shrc line='alias {{ item.key }}=\"{{ item.value }}\"' insertafter='# aliases'
#   with_dict: "{{aliases}}"
#   vars:
#     aliases:
#       docker_clean_images: 'docker rmi \$(docker images -a --filter=dangling=true -q) --force'
#       docker_clean_containers: 'docker rm -v \$(docker ps -a -q -f status=exited)'
#       docker_clean_volumes: 'docker volume rm \$(docker volume ls -qf dangling=true)'
#       docker_clean: 'docker_clean_images; docker_clean_containers; docker_clean_volumes'
#       # time_estimate: 'docker run --rm -v \$(pwd):/code khor/git-hours'

- name: aliases into shrc
  tags: debug
  blockinfile:
    dest: ~/.shrc
    create: yes
    marker: "# ANSIBLE {mark} docker alias {{item.key}}"
    block: |
      alias {{ item.key }}="{{ item.value }}"
  with_dict: "{{aliases}}"
  vars:
    aliases:
      docker_clean_images: 'docker rmi \$(docker images -a --filter=dangling=true -q) --force'
      docker_clean_containers: 'docker rm -v \$(docker ps -a -q -f status=exited)'
      docker_kill_all: 'docker update --restart=no \$(docker ps -a -q); docker kill -v -f \$(docker ps -a -q); docker rm -v -f \$(docker ps -a -q)'
      docker_clean_volumes: 'docker volume rm \$(docker volume ls -qf dangling=true)'
      docker_clean: 'docker_clean_images; docker_clean_containers; docker_clean_volumes'
      # time_estimate: 'docker run --rm -v \$(pwd):/code khor/git-hours'

- include: "{{ role_path }}/modules/getDpkg.yml"
  tags: ubuntu
  with_items:
    - { name: 'docker', url: 'https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb' }
- name: make docker run without sudo
  tags: ubuntu
  become: true
  become_method: sudo
  shell: |
    groupadd docker
    usermod -aG docker {{ ansible_env.USER }}

- name: add docker-compose
  tags: ubuntu
  become: true
  become_method: sudo
  shell: curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  async: 45
  poll: 5
    

  