---

- name: Show hidden files in finder by default
  osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true state=present

- name: Reduce keyboard key repeat delay
  osx_defaults: key=InitialKeyRepeat type=int value=15 state=present

- name: Increase keyboard key repeat speed
  osx_defaults: key=KeyRepeat type=int value=2

- name: Set cron shell
  cron: name=SHELL env=yes value=/bin/zsh

- name: Set cron path
  cron: name=PATH env=yes value=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

- name: Create Git configs
  git_config: scope=global name={{ item.name }} value={{ item.value }}
  with_items:
    - { name: 'user.name', value: 'nmrshll' }
    - { name: 'core.excludesfile', value: '~/.gitignore_global' }
    # - { name: 'core.pager', value: 'diff-so-fancy | less --tabs=1,5 -R' }
    # - { name: 'color.branch', value: "always" }
    # - { name: 'color.diff', value: "auto" }
    # - { name: 'color.interactive', value: "always" }
    # - { name: 'color.status', value: "always" }
    # - { name: 'color.ui', value: "always" }
    # - { name: 'color.diff-highlight.oldNormal', value: "red bold" }
    # - { name: 'color.diff-highlight.oldHighlight', value: "red bold 52" }
    # - { name: 'color.diff-highlight.newNormal', value: "green bold" }
    # - { name: 'color.diff-highlight.newHighlight', value: "green bold 22" }
    # - { name: 'core.autocrlf', value: "input" }
    # - { name: 'core.whitespace', value: "trailing-space,space-before-tab,cr-at-eol" }
    # - { name: 'alias.cod', value: "checkout development" }
    # - { name: 'alias.cos', value: "checkout staging" }
    # - { name: 'alias.cop', value: "checkout production" }
    # - { name: 'alias.md', value: "merge development" }
    # - { name: 'alias.last', value: "log -1 HEAD" }
    - { name: 'alias.undo-commit', value: "reset HEAD~" }
    - { name: 'alias.headf', value: 'log --graph --pretty=tformat:"%Cblue %h %Cgreen %ad %Cred %an %Creset %s %Cblue%d%Creset" --abbrev-commit --decorate --parents --date=short -n32' }
    # - { name: 'diff.tool', value: 'diffmerge' }
    # - { name: 'difftool.diffmerge.cmd', value: 'diffmerge "$LOCAL" "$REMOTE"' }
    - { name: 'format.pretty', value: "oneline" }
    # - { name: 'merge.tool', value: 'diffmerge' }
    # - { name: 'mergetool.diffmerge.cmd', value: 'diffmerge --merge --result="$MERGED" "$LOCAL" "$(if test -f \"$BASE\"; then echo \"$BASE\"; else echo \"$LOCAL\"; fi)\" \"$REMOTE\"' }
    # - { name: 'mergetool.diffmerge.trustExitCode', value: true }
    # - { name: 'push.default', value: "simple" }
    # - { name: 'push.followTags', value: true }
    # - { name: 'tag.sort', value: 'version:refname' } 
    # - { name: 'pull.rebase', value: true }

- name: Create system aliases
  lineinfile: dest=~/.shrc line='alias {{ item.key }}=\"{{ item.value }}\"' insertafter='# aliases'
  with_dict: "{{aliases}}"
  vars:
    aliases:
      # gcod: "git checkout development"
      # gcos: "git checkout staging"
      # gcop: "git checkout production"
      # gmd: "git merge development"
      # gms: "git merge staging"
      # gmp: "git merge production"
      # gc: "git commit -m"
      # gs: git status
      # gpl: git pull
      # gp: git push  
      # gpt: "git push --tags"
      # gph: git push
      # update: "git push && gcos && gmd && git push && gcop && gms && git push && gcod"
      docker_clean_images: 'docker rmi \$(docker images -a --filter=dangling=true -q) --force'
      docker_clean_containers: 'docker rm -v \$(docker ps -a -q -f status=exited)'
      docker_clean_volumes: 'docker volume rm \$(docker volume ls -qf dangling=true)'
      docker_clean: docker_clean_images; docker_clean_containers; docker_clean_volumes
      # time_estimate: 'docker run --rm -v \$(pwd):/code khor/git-hours'
      # git: hub
      # wherefiles: "lsof | awk '{ print $2; }' | uniq -c | sort -rn | head"
      # ls: exa
      copy_ssh: "cat ~/.ssh/id_rsa.pub | pbcopy"
      chrome: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
      octal: "stat -f '%A %a %N'"
      ip: "curl icanhazip.com"
